[env:esp32-c3]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  https://github.com/Anrijs/Aranet4-ESP32.git#3cf3386dd297f0e9e6d0736bb7e5b51cbafe6600
  h2zero/NimBLE-Arduino@1.4.3
